// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Access struct {
	ID             string  `json:"id"`
	Code           int     `json:"code"`
	Duration       int     `json:"duration"`
	Error          *string `json:"error"`
	HTTPS          bool    `json:"https"`
	Method         string  `json:"method"`
	Searchduration int     `json:"searchduration"`
	URI            string  `json:"uri"`
	Writeerr       *string `json:"writeerr"`
}

type APIAccess struct {
	ID       string  `json:"id"`
	Duration int     `json:"duration"`
	Error    *string `json:"error"`
	Request  string  `json:"request"`
}

type NewSetting struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type Ping struct {
	Uptime int `json:"uptime"`
}

type Return struct {
	Ok   bool   `json:"ok"`
	Info string `json:"info"`
}

type Setting struct {
	Name  string `json:"name"`
	Value string `json:"value"`
	Admin bool   `json:"admin"`
}
