name: Rust-Gamemanager

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd Gamemanager && cargo build --verbose
    - name: Run tests
      run: cd Gamemanager && cargo test --verbose
